
default: &default
  adapter: postgresql
  encoding: utf8

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: blog-development-database


test:
  <<: *default
  database: blog_api_test


production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: <%= ENV["BLOG_API_DATABASE_PASSWORD"] %>
